import json

log = """{
  "LettuceMercenaries": [
    {
      "changeCurrency": 554,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(554)",
      "ReadColor": "black",
      "ReadLevel": "Level: 7 +0",
      "ReadCurrency": "Coin: 1193 +0",
      "Level": 7,
      "Currency": 1193,
      "Owned": true,
      "ChnName": "古夫·符文图腾",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 565,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(565)",
      "ReadColor": "black",
      "ReadLevel": "Level: 30 +0",
      "ReadCurrency": "Coin: 1093 +0",
      "Level": 30,
      "Currency": 1093,
      "Owned": true,
      "ChnName": "泽瑞拉",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 798,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(798)",
      "ReadColor": "black",
      "ReadLevel": "Level: 30 +0",
      "ReadCurrency": "Coin: 958 +0",
      "Level": 30,
      "Currency": 958,
      "Owned": true,
      "ChnName": "凯瑞尔·罗姆",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 615,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(615)",
      "ReadColor": "black",
      "ReadLevel": "Level: 1 +0",
      "ReadCurrency": "Coin: 714 +0",
      "Level": 1,
      "Currency": 714,
      "Owned": true,
      "ChnName": "瓦尔登·晨拥",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 368,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(368)",
      "ReadColor": "black",
      "ReadLevel": "Level: 30 +0",
      "ReadCurrency": "Coin: 543 +0",
      "Level": 30,
      "Currency": 543,
      "Owned": true,
      "ChnName": "塔维什·雷矛",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 341,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(341)",
      "ReadColor": "black",
      "ReadLevel": "Level: 30 +0",
      "ReadCurrency": "Coin: 539 +0",
      "Level": 30,
      "Currency": 539,
      "Owned": true,
      "ChnName": "米尔豪斯·法力风暴",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 189,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(189)",
      "ReadColor": "gray",
      "ReadLevel": "Level: 1 +0",
      "ReadCurrency": "Coin: 420 +0",
      "Level": 1,
      "Currency": 420,
      "Owned": false,
      "ChnName": "吉安娜·普罗德摩尔",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 237,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(237)",
      "ReadColor": "gray",
      "ReadLevel": "Level: 1 +0",
      "ReadCurrency": "Coin: 415 +0",
      "Level": 1,
      "Currency": 415,
      "Owned": false,
      "ChnName": "巫妖王",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 206,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(206)",
      "ReadColor": "gray",
      "ReadLevel": "Level: 1 +0",
      "ReadCurrency": "Coin: 396 +0",
      "Level": 1,
      "Currency": 396,
      "Owned": false,
      "ChnName": "安度因·乌瑞恩",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 168,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(168)",
      "ReadColor": "gray",
      "ReadLevel": "Level: 1 +0",
      "ReadCurrency": "Coin: 394 +0",
      "Level": 1,
      "Currency": 394,
      "Owned": false,
      "ChnName": "加拉克苏斯大王",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 161,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(161)",
      "ReadColor": "gray",
      "ReadLevel": "Level: 1 +0",
      "ReadCurrency": "Coin: 343 +0",
      "Level": 1,
      "Currency": 343,
      "Owned": false,
      "ChnName": "古尔丹",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": -87,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(-87)",
      "ReadColor": "black",
      "ReadLevel": "Level: 7 +0",
      "ReadCurrency": "Coin: 341 +0",
      "Level": 7,
      "Currency": 341,
      "Owned": true,
      "ChnName": "布鲁坎",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 191,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(191)",
      "ReadColor": "gray",
      "ReadLevel": "Level: 1 +0",
      "ReadCurrency": "Coin: 339 +0",
      "Level": 1,
      "Currency": 339,
      "Owned": false,
      "ChnName": "迪亚波罗",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 185,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(185)",
      "ReadColor": "gray",
      "ReadLevel": "Level: 1 +0",
      "ReadCurrency": "Coin: 319 +0",
      "Level": 1,
      "Currency": 319,
      "Owned": false,
      "ChnName": "阿莱克丝塔萨",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 126,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(126)",
      "ReadColor": "gray",
      "ReadLevel": "Level: 1 +0",
      "ReadCurrency": "Coin: 280 +0",
      "Level": 1,
      "Currency": 280,
      "Owned": false,
      "ChnName": "加尔鲁什·地狱咆哮",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 164,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(164)",
      "ReadColor": "gray",
      "ReadLevel": "Level: 1 +0",
      "ReadCurrency": "Coin: 277 +0",
      "Level": 1,
      "Currency": 277,
      "Owned": false,
      "ChnName": "乌瑟尔",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": -88,
      "changeLevel": 23,
      "ReadChangeLevel": "(23)",
      "ReadChangeCurrency": "(-88)",
      "ReadColor": "black",
      "ReadLevel": "Level: 30 +23",
      "ReadCurrency": "Coin: 230 +23",
      "Level": 30,
      "Currency": 230,
      "Owned": true,
      "ChnName": "拉索利安",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 135,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(135)",
      "ReadColor": "black",
      "ReadLevel": "Level: 30 +0",
      "ReadCurrency": "Coin: 166 +0",
      "Level": 30,
      "Currency": 166,
      "Owned": true,
      "ChnName": "库尔特鲁斯·陨烬",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 44,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(44)",
      "ReadColor": "black",
      "ReadLevel": "Level: 30 +0",
      "ReadCurrency": "Coin: 130 +0",
      "Level": 30,
      "Currency": 130,
      "Owned": true,
      "ChnName": "安东尼达斯",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 93,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(93)",
      "ReadColor": "black",
      "ReadLevel": "Level: 30 +0",
      "ReadCurrency": "Coin: 124 +0",
      "Level": 30,
      "Currency": 124,
      "Owned": true,
      "ChnName": "凯恩·血蹄",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 75,
      "changeLevel": 29,
      "ReadChangeLevel": "(29)",
      "ReadChangeCurrency": "(75)",
      "ReadColor": "black",
      "ReadLevel": "Level: 30 +29",
      "ReadCurrency": "Coin: 121 +29",
      "Level": 30,
      "Currency": 121,
      "Owned": true,
      "ChnName": "老瞎眼",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": -15,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(-15)",
      "ReadColor": "black",
      "ReadLevel": "Level: 30 +0",
      "ReadCurrency": "Coin: 107 +0",
      "Level": 30,
      "Currency": 107,
      "Owned": true,
      "ChnName": "格鲁尔",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 30,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(30)",
      "ReadColor": "black",
      "ReadLevel": "Level: 30 +0",
      "ReadCurrency": "Coin: 94 +0",
      "Level": 30,
      "Currency": 94,
      "Owned": true,
      "ChnName": "洛卡拉",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 54,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(54)",
      "ReadColor": "black",
      "ReadLevel": "Level: 30 +0",
      "ReadCurrency": "Coin: 81 +0",
      "Level": 30,
      "Currency": 81,
      "Owned": true,
      "ChnName": "先知维伦",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 35,
      "changeLevel": 29,
      "ReadChangeLevel": "(29)",
      "ReadChangeCurrency": "(35)",
      "ReadColor": "black",
      "ReadLevel": "Level: 30 +29",
      "ReadCurrency": "Coin: 80 +29",
      "Level": 30,
      "Currency": 80,
      "Owned": true,
      "ChnName": "提里奥·弗丁",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 45,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(45)",
      "ReadColor": "black",
      "ReadLevel": "Level: 30 +0",
      "ReadCurrency": "Coin: 78 +0",
      "Level": 30,
      "Currency": 78,
      "Owned": true,
      "ChnName": "瓦里安·乌瑞恩",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 78,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(78)",
      "ReadColor": "black",
      "ReadLevel": "Level: 30 +0",
      "ReadCurrency": "Coin: 78 +0",
      "Level": 30,
      "Currency": 78,
      "Owned": true,
      "ChnName": "光明之翼",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": -60,
      "changeLevel": 28,
      "ReadChangeLevel": "(28)",
      "ReadChangeCurrency": "(-60)",
      "ReadColor": "black",
      "ReadLevel": "Level: 29 +28",
      "ReadCurrency": "Coin: 73 +28",
      "Level": 29,
      "Currency": 73,
      "Owned": true,
      "ChnName": "穆坦努斯",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": -83,
      "changeLevel": 29,
      "ReadChangeLevel": "(29)",
      "ReadChangeCurrency": "(-83)",
      "ReadColor": "black",
      "ReadLevel": "Level: 30 +29",
      "ReadCurrency": "Coin: 67 +29",
      "Level": 30,
      "Currency": 67,
      "Owned": true,
      "ChnName": "神谕者摩戈尔",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": -160,
      "changeLevel": 28,
      "ReadChangeLevel": "(28)",
      "ReadChangeCurrency": "(-160)",
      "ReadColor": "black",
      "ReadLevel": "Level: 29 +28",
      "ReadCurrency": "Coin: 66 +28",
      "Level": 29,
      "Currency": 66,
      "Owned": true,
      "ChnName": "暴龙王克鲁什",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": -15,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(-15)",
      "ReadColor": "black",
      "ReadLevel": "Level: 19 +0",
      "ReadCurrency": "Coin: 65 +0",
      "Level": 19,
      "Currency": 65,
      "Owned": true,
      "ChnName": "指挥官沃恩",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 15,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(15)",
      "ReadColor": "black",
      "ReadLevel": "Level: 30 +0",
      "ReadCurrency": "Coin: 61 +0",
      "Level": 30,
      "Currency": 61,
      "Owned": true,
      "ChnName": "格罗玛什·地狱咆哮",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 9,
      "changeLevel": 23,
      "ReadChangeLevel": "(23)",
      "ReadChangeCurrency": "(9)",
      "ReadColor": "black",
      "ReadLevel": "Level: 30 +23",
      "ReadCurrency": "Coin: 61 +23",
      "Level": 30,
      "Currency": 61,
      "Owned": true,
      "ChnName": "伊利丹·怒风",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": -24,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(-24)",
      "ReadColor": "black",
      "ReadLevel": "Level: 30 +0",
      "ReadCurrency": "Coin: 57 +0",
      "Level": 30,
      "Currency": 57,
      "Owned": true,
      "ChnName": "安娜科德拉",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": -64,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(-64)",
      "ReadColor": "black",
      "ReadLevel": "Level: 30 +0",
      "ReadCurrency": "Coin: 54 +0",
      "Level": 30,
      "Currency": 54,
      "Owned": true,
      "ChnName": "剑圣萨穆罗",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": -52,
      "changeLevel": 28,
      "ReadChangeLevel": "(28)",
      "ReadChangeCurrency": "(-52)",
      "ReadColor": "black",
      "ReadLevel": "Level: 29 +28",
      "ReadCurrency": "Coin: 49 +28",
      "Level": 29,
      "Currency": 49,
      "Owned": true,
      "ChnName": "萨鲁法尔",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": -20,
      "changeLevel": 23,
      "ReadChangeLevel": "(23)",
      "ReadChangeCurrency": "(-20)",
      "ReadColor": "black",
      "ReadLevel": "Level: 30 +23",
      "ReadCurrency": "Coin: 46 +23",
      "Level": 30,
      "Currency": 46,
      "Owned": true,
      "ChnName": "玛法里奥·怒风",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": -169,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(-169)",
      "ReadColor": "black",
      "ReadLevel": "Level: 30 +0",
      "ReadCurrency": "Coin: 45 +0",
      "Level": 30,
      "Currency": 45,
      "Owned": true,
      "ChnName": "穆克拉",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 21,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(21)",
      "ReadColor": "black",
      "ReadLevel": "Level: 30 +0",
      "ReadCurrency": "Coin: 37 +0",
      "Level": 30,
      "Currency": 37,
      "Owned": true,
      "ChnName": "希尔瓦娜斯·风行者",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": -88,
      "changeLevel": 29,
      "ReadChangeLevel": "(29)",
      "ReadChangeCurrency": "(-88)",
      "ReadColor": "black",
      "ReadLevel": "Level: 30 +29",
      "ReadCurrency": "Coin: 36 +29",
      "Level": 30,
      "Currency": 36,
      "Owned": true,
      "ChnName": "泰兰德",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": -47,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(-47)",
      "ReadColor": "black",
      "ReadLevel": "Level: 30 +0",
      "ReadCurrency": "Coin: 33 +0",
      "Level": 30,
      "Currency": 33,
      "Owned": true,
      "ChnName": "萨尔",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": -273,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(-273)",
      "ReadColor": "black",
      "ReadLevel": "Level: 1 +0",
      "ReadCurrency": "Coin: 25 +0",
      "Level": 1,
      "Currency": 25,
      "Owned": true,
      "ChnName": "迦顿男爵",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": -37,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(-37)",
      "ReadColor": "black",
      "ReadLevel": "Level: 30 +0",
      "ReadCurrency": "Coin: 15 +0",
      "Level": 30,
      "Currency": 15,
      "Owned": true,
      "ChnName": "塔姆辛·罗姆",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": -103,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(-103)",
      "ReadColor": "black",
      "ReadLevel": "Level: 30 +0",
      "ReadCurrency": "Coin: 13 +0",
      "Level": 30,
      "Currency": 13,
      "Owned": true,
      "ChnName": "考内留斯·罗姆",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": -34,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(-34)",
      "ReadColor": "black",
      "ReadLevel": "Level: 30 +0",
      "ReadCurrency": "Coin: 10 +0",
      "Level": 30,
      "Currency": 10,
      "Owned": true,
      "ChnName": "雷克萨",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": -204,
      "changeLevel": 28,
      "ReadChangeLevel": "(28)",
      "ReadChangeCurrency": "(-204)",
      "ReadColor": "black",
      "ReadLevel": "Level: 29 +28",
      "ReadCurrency": "Coin: 10 +28",
      "Level": 29,
      "Currency": 10,
      "Owned": true,
      "ChnName": "娜塔莉·塞林",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": -20,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(-20)",
      "ReadColor": "black",
      "ReadLevel": "Level: 30 +0",
      "ReadCurrency": "Coin: 10 +0",
      "Level": 30,
      "Currency": 10,
      "Owned": true,
      "ChnName": "玛诺洛斯",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": -76,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(-76)",
      "ReadColor": "black",
      "ReadLevel": "Level: 1 +0",
      "ReadCurrency": "Coin: 8 +0",
      "Level": 1,
      "Currency": 8,
      "Owned": true,
      "ChnName": "沃金",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": -151,
      "changeLevel": 29,
      "ReadChangeLevel": "(29)",
      "ReadChangeCurrency": "(-151)",
      "ReadColor": "black",
      "ReadLevel": "Level: 30 +29",
      "ReadCurrency": "Coin: 7 +29",
      "Level": 30,
      "Currency": 7,
      "Owned": true,
      "ChnName": "闪狐",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": -82,
      "changeLevel": 29,
      "ReadChangeLevel": "(29)",
      "ReadChangeCurrency": "(-82)",
      "ReadColor": "black",
      "ReadLevel": "Level: 30 +29",
      "ReadCurrency": "Coin: 0 +29",
      "Level": 30,
      "Currency": 0,
      "Owned": true,
      "ChnName": "斯卡布斯·刀油",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": -341,
      "changeLevel": 29,
      "ReadChangeLevel": "(29)",
      "ReadChangeCurrency": "(-341)",
      "ReadColor": "black",
      "ReadLevel": "Level: 30 +29",
      "ReadCurrency": "Coin: 0 +29",
      "Level": 30,
      "Currency": 0,
      "Owned": true,
      "ChnName": "拉格纳罗斯",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": -46,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(-46)",
      "ReadColor": "gray",
      "ReadLevel": "Level: 1 +0",
      "ReadCurrency": "Coin: 0 +0",
      "Level": 1,
      "Currency": 0,
      "Owned": false,
      "ChnName": "时光修补匠托奇",
      "Attack": -1,
      "Health": -1
    }
  ],
  "RecordTime": "18小时 10分 29秒",
  "RecordCurrency": "10701",
  "RecordLevel": "1122",
  "OldTime": "2021-10-25T06:02:26.3209832+08:00",
  "OldLettuceMercenaries": [
    {
      "changeCurrency": 0,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(0)",
      "ReadColor": "black",
      "ReadLevel": "Level: 7 +0",
      "ReadCurrency": "Coin: 639 +0",
      "Level": 7,
      "Currency": 639,
      "Owned": true,
      "ChnName": "古夫·符文图腾",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 0,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(0)",
      "ReadColor": "black",
      "ReadLevel": "Level: 30 +0",
      "ReadCurrency": "Coin: 528 +0",
      "Level": 30,
      "Currency": 528,
      "Owned": true,
      "ChnName": "泽瑞拉",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 0,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(0)",
      "ReadColor": "black",
      "ReadLevel": "Level: 7 +0",
      "ReadCurrency": "Coin: 428 +0",
      "Level": 7,
      "Currency": 428,
      "Owned": true,
      "ChnName": "布鲁坎",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 0,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(0)",
      "ReadColor": "gray",
      "ReadLevel": "Level: 1 +0",
      "ReadCurrency": "Coin: 341 +0",
      "Level": 1,
      "Currency": 341,
      "Owned": false,
      "ChnName": "拉格纳罗斯",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 0,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(0)",
      "ReadColor": "black",
      "ReadLevel": "Level: 7 +0",
      "ReadCurrency": "Coin: 318 +0",
      "Level": 7,
      "Currency": 318,
      "Owned": true,
      "ChnName": "拉索利安",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 0,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(0)",
      "ReadColor": "gray",
      "ReadLevel": "Level: 1 +0",
      "ReadCurrency": "Coin: 298 +0",
      "Level": 1,
      "Currency": 298,
      "Owned": false,
      "ChnName": "迦顿男爵",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 0,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(0)",
      "ReadColor": "gray",
      "ReadLevel": "Level: 1 +0",
      "ReadCurrency": "Coin: 231 +0",
      "Level": 1,
      "Currency": 231,
      "Owned": false,
      "ChnName": "吉安娜·普罗德摩尔",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 0,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(0)",
      "ReadColor": "gray",
      "ReadLevel": "Level: 1 +0",
      "ReadCurrency": "Coin: 226 +0",
      "Level": 1,
      "Currency": 226,
      "Owned": false,
      "ChnName": "加拉克苏斯大王",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 0,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(0)",
      "ReadColor": "gray",
      "ReadLevel": "Level: 1 +0",
      "ReadCurrency": "Coin: 226 +0",
      "Level": 1,
      "Currency": 226,
      "Owned": false,
      "ChnName": "暴龙王克鲁什",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 0,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(0)",
      "ReadColor": "gray",
      "ReadLevel": "Level: 1 +0",
      "ReadCurrency": "Coin: 214 +0",
      "Level": 1,
      "Currency": 214,
      "Owned": false,
      "ChnName": "娜塔莉·塞林",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 0,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(0)",
      "ReadColor": "black",
      "ReadLevel": "Level: 30 +0",
      "ReadCurrency": "Coin: 214 +0",
      "Level": 30,
      "Currency": 214,
      "Owned": true,
      "ChnName": "穆克拉",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 0,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(0)",
      "ReadColor": "black",
      "ReadLevel": "Level: 30 +0",
      "ReadCurrency": "Coin: 198 +0",
      "Level": 30,
      "Currency": 198,
      "Owned": true,
      "ChnName": "米尔豪斯·法力风暴",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 0,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(0)",
      "ReadColor": "black",
      "ReadLevel": "Level: 1 +0",
      "ReadCurrency": "Coin: 190 +0",
      "Level": 1,
      "Currency": 190,
      "Owned": true,
      "ChnName": "安度因·乌瑞恩",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 0,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(0)",
      "ReadColor": "gray",
      "ReadLevel": "Level: 1 +0",
      "ReadCurrency": "Coin: 182 +0",
      "Level": 1,
      "Currency": 182,
      "Owned": false,
      "ChnName": "古尔丹",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 0,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(0)",
      "ReadColor": "black",
      "ReadLevel": "Level: 1 +0",
      "ReadCurrency": "Coin: 178 +0",
      "Level": 1,
      "Currency": 178,
      "Owned": true,
      "ChnName": "巫妖王",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 0,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(0)",
      "ReadColor": "black",
      "ReadLevel": "Level: 30 +0",
      "ReadCurrency": "Coin: 175 +0",
      "Level": 30,
      "Currency": 175,
      "Owned": true,
      "ChnName": "塔维什·雷矛",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 0,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(0)",
      "ReadColor": "black",
      "ReadLevel": "Level: 30 +0",
      "ReadCurrency": "Coin: 160 +0",
      "Level": 30,
      "Currency": 160,
      "Owned": true,
      "ChnName": "凯瑞尔·罗姆",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 0,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(0)",
      "ReadColor": "black",
      "ReadLevel": "Level: 1 +0",
      "ReadCurrency": "Coin: 158 +0",
      "Level": 1,
      "Currency": 158,
      "Owned": true,
      "ChnName": "闪狐",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 0,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(0)",
      "ReadColor": "gray",
      "ReadLevel": "Level: 1 +0",
      "ReadCurrency": "Coin: 154 +0",
      "Level": 1,
      "Currency": 154,
      "Owned": false,
      "ChnName": "加尔鲁什·地狱咆哮",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 0,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(0)",
      "ReadColor": "black",
      "ReadLevel": "Level: 1 +0",
      "ReadCurrency": "Coin: 150 +0",
      "Level": 1,
      "Currency": 150,
      "Owned": true,
      "ChnName": "神谕者摩戈尔",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 0,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(0)",
      "ReadColor": "gray",
      "ReadLevel": "Level: 1 +0",
      "ReadCurrency": "Coin: 148 +0",
      "Level": 1,
      "Currency": 148,
      "Owned": false,
      "ChnName": "迪亚波罗",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 0,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(0)",
      "ReadColor": "gray",
      "ReadLevel": "Level: 1 +0",
      "ReadCurrency": "Coin: 134 +0",
      "Level": 1,
      "Currency": 134,
      "Owned": false,
      "ChnName": "阿莱克丝塔萨",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 0,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(0)",
      "ReadColor": "black",
      "ReadLevel": "Level: 1 +0",
      "ReadCurrency": "Coin: 133 +0",
      "Level": 1,
      "Currency": 133,
      "Owned": true,
      "ChnName": "穆坦努斯",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 0,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(0)",
      "ReadColor": "black",
      "ReadLevel": "Level: 1 +0",
      "ReadCurrency": "Coin: 124 +0",
      "Level": 1,
      "Currency": 124,
      "Owned": true,
      "ChnName": "泰兰德",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 0,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(0)",
      "ReadColor": "black",
      "ReadLevel": "Level: 30 +0",
      "ReadCurrency": "Coin: 122 +0",
      "Level": 30,
      "Currency": 122,
      "Owned": true,
      "ChnName": "格鲁尔",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 0,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(0)",
      "ReadColor": "black",
      "ReadLevel": "Level: 30 +0",
      "ReadCurrency": "Coin: 118 +0",
      "Level": 30,
      "Currency": 118,
      "Owned": true,
      "ChnName": "剑圣萨穆罗",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 0,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(0)",
      "ReadColor": "black",
      "ReadLevel": "Level: 30 +0",
      "ReadCurrency": "Coin: 116 +0",
      "Level": 30,
      "Currency": 116,
      "Owned": true,
      "ChnName": "考内留斯·罗姆",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 0,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(0)",
      "ReadColor": "black",
      "ReadLevel": "Level: 1 +0",
      "ReadCurrency": "Coin: 113 +0",
      "Level": 1,
      "Currency": 113,
      "Owned": true,
      "ChnName": "乌瑟尔",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 0,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(0)",
      "ReadColor": "black",
      "ReadLevel": "Level: 1 +0",
      "ReadCurrency": "Coin: 101 +0",
      "Level": 1,
      "Currency": 101,
      "Owned": true,
      "ChnName": "萨鲁法尔",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 0,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(0)",
      "ReadColor": "black",
      "ReadLevel": "Level: 1 +0",
      "ReadCurrency": "Coin: 99 +0",
      "Level": 1,
      "Currency": 99,
      "Owned": true,
      "ChnName": "瓦尔登·晨拥",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 0,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(0)",
      "ReadColor": "black",
      "ReadLevel": "Level: 30 +0",
      "ReadCurrency": "Coin: 86 +0",
      "Level": 30,
      "Currency": 86,
      "Owned": true,
      "ChnName": "安东尼达斯",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 0,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(0)",
      "ReadColor": "gray",
      "ReadLevel": "Level: 1 +0",
      "ReadCurrency": "Coin: 84 +0",
      "Level": 1,
      "Currency": 84,
      "Owned": false,
      "ChnName": "沃金",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 0,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(0)",
      "ReadColor": "black",
      "ReadLevel": "Level: 1 +0",
      "ReadCurrency": "Coin: 82 +0",
      "Level": 1,
      "Currency": 82,
      "Owned": true,
      "ChnName": "斯卡布斯·刀油",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 0,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(0)",
      "ReadColor": "black",
      "ReadLevel": "Level: 30 +0",
      "ReadCurrency": "Coin: 81 +0",
      "Level": 30,
      "Currency": 81,
      "Owned": true,
      "ChnName": "安娜科德拉",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 0,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(0)",
      "ReadColor": "black",
      "ReadLevel": "Level: 30 +0",
      "ReadCurrency": "Coin: 80 +0",
      "Level": 30,
      "Currency": 80,
      "Owned": true,
      "ChnName": "萨尔",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 0,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(0)",
      "ReadColor": "black",
      "ReadLevel": "Level: 19 +0",
      "ReadCurrency": "Coin: 80 +0",
      "Level": 19,
      "Currency": 80,
      "Owned": true,
      "ChnName": "指挥官沃恩",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 0,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(0)",
      "ReadColor": "black",
      "ReadLevel": "Level: 7 +0",
      "ReadCurrency": "Coin: 66 +0",
      "Level": 7,
      "Currency": 66,
      "Owned": true,
      "ChnName": "玛法里奥·怒风",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 0,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(0)",
      "ReadColor": "black",
      "ReadLevel": "Level: 30 +0",
      "ReadCurrency": "Coin: 64 +0",
      "Level": 30,
      "Currency": 64,
      "Owned": true,
      "ChnName": "洛卡拉",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 0,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(0)",
      "ReadColor": "black",
      "ReadLevel": "Level: 7 +0",
      "ReadCurrency": "Coin: 52 +0",
      "Level": 7,
      "Currency": 52,
      "Owned": true,
      "ChnName": "伊利丹·怒风",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 0,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(0)",
      "ReadColor": "black",
      "ReadLevel": "Level: 30 +0",
      "ReadCurrency": "Coin: 52 +0",
      "Level": 30,
      "Currency": 52,
      "Owned": true,
      "ChnName": "塔姆辛·罗姆",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 0,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(0)",
      "ReadColor": "black",
      "ReadLevel": "Level: 30 +0",
      "ReadCurrency": "Coin: 46 +0",
      "Level": 30,
      "Currency": 46,
      "Owned": true,
      "ChnName": "格罗玛什·地狱咆哮",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 0,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(0)",
      "ReadColor": "black",
      "ReadLevel": "Level: 1 +0",
      "ReadCurrency": "Coin: 46 +0",
      "Level": 1,
      "Currency": 46,
      "Owned": true,
      "ChnName": "老瞎眼",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 0,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(0)",
      "ReadColor": "gray",
      "ReadLevel": "Level: 1 +0",
      "ReadCurrency": "Coin: 46 +0",
      "Level": 1,
      "Currency": 46,
      "Owned": false,
      "ChnName": "时光修补匠托奇",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 0,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(0)",
      "ReadColor": "black",
      "ReadLevel": "Level: 1 +0",
      "ReadCurrency": "Coin: 45 +0",
      "Level": 1,
      "Currency": 45,
      "Owned": true,
      "ChnName": "提里奥·弗丁",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 0,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(0)",
      "ReadColor": "black",
      "ReadLevel": "Level: 30 +0",
      "ReadCurrency": "Coin: 44 +0",
      "Level": 30,
      "Currency": 44,
      "Owned": true,
      "ChnName": "雷克萨",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 0,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(0)",
      "ReadColor": "black",
      "ReadLevel": "Level: 30 +0",
      "ReadCurrency": "Coin: 33 +0",
      "Level": 30,
      "Currency": 33,
      "Owned": true,
      "ChnName": "瓦里安·乌瑞恩",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 0,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(0)",
      "ReadColor": "black",
      "ReadLevel": "Level: 30 +0",
      "ReadCurrency": "Coin: 31 +0",
      "Level": 30,
      "Currency": 31,
      "Owned": true,
      "ChnName": "库尔特鲁斯·陨烬",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 0,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(0)",
      "ReadColor": "black",
      "ReadLevel": "Level: 30 +0",
      "ReadCurrency": "Coin: 31 +0",
      "Level": 30,
      "Currency": 31,
      "Owned": true,
      "ChnName": "凯恩·血蹄",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 0,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(0)",
      "ReadColor": "black",
      "ReadLevel": "Level: 30 +0",
      "ReadCurrency": "Coin: 30 +0",
      "Level": 30,
      "Currency": 30,
      "Owned": true,
      "ChnName": "玛诺洛斯",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 0,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(0)",
      "ReadColor": "black",
      "ReadLevel": "Level: 30 +0",
      "ReadCurrency": "Coin: 27 +0",
      "Level": 30,
      "Currency": 27,
      "Owned": true,
      "ChnName": "先知维伦",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 0,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(0)",
      "ReadColor": "black",
      "ReadLevel": "Level: 30 +0",
      "ReadCurrency": "Coin: 16 +0",
      "Level": 30,
      "Currency": 16,
      "Owned": true,
      "ChnName": "希尔瓦娜斯·风行者",
      "Attack": -1,
      "Health": -1
    },
    {
      "changeCurrency": 0,
      "changeLevel": 0,
      "ReadChangeLevel": "(0)",
      "ReadChangeCurrency": "(0)",
      "ReadColor": "black",
      "ReadLevel": "Level: 30 +0",
      "ReadCurrency": "Coin: 0 +0",
      "Level": 30,
      "Currency": 0,
      "Owned": true,
      "ChnName": "光明之翼",
      "Attack": -1,
      "Health": -1
    }
  ]
}"""

data = json.loads(log)
print(data["LettuceMercenaries"])
for item in data["LettuceMercenaries"]:
    print("{0} {1} {2}".format())
